### ISSUE TITLE
Is ssh authentication supported? 

### ISSUE THREAD

**Issue by kirkilj** [SanderRonde/VSCode-Gerrit#18]
Our Gerrit server requires ssh authentication, which works fine with git review CLI. Gerrit version is 2.16.22

**Comment by SanderRonde** [comment]
If you're asking whether it's possible to replace the HTTP credentials with SSH authentication, then the answer is unfortunately no. Gerrit only allows access to the API with the HTTP credentials and only exposes a few APIs to the SSH-authenticated flow.

**Comment by kirkilj** [comment]
Although not as full featured, there's another VSCode Gerrit extension I'm evaluating ([Gerrit-View](https://github.com/Gruntfuggly/gerrit-view/blob/master/gerrit.js)) that does support ssh authentication through [an ssh library](https://github.com/steelbrain/node-ssh).

After looking through the gerrit-view code, it's clear it's issuing commands via the CLI over SSH rather than HTTP-based requests. I'll ask our Gerrit admins if HTTP access is allowed. The devops folks can be wary of developers writing runaway scripts that can hammer Gerrit.

**Comment by SanderRonde** [comment]
Yeah it looks like that extension is a lot more basic and just lists the patches. This one also allows you to do other stuff like viewing/posting comments and replying to patches. Those things are not possible over SSH so they need HTTP access.

To ease your admins' pain, your rights are the same for SSH and HTTP requests. You can't really do more harm than you could do over SSH.

I'll be closing this issue now but feel free to reply if you have any more questions.
