### ISSUE TITLE
Hello, how to setup Gerrit extension on VS code?

### ISSUE THREAD

**Issue by CoolNzzz** [SanderRonde/VSCode-Gerrit#22]
Hello, I'm a newbie on VS code with Gerrit. 
I have learned about that and try to use. 

Anyway I want to integrate your Gerrit plugin to VS code. But I couldn't do that now.  
Also I could not find any manual or guide.  

My status is
I just success installed. And I write Gerrit configuration section in settings.json.  
After that, if I use menu of gerrit, nothing changed. Do I need more setup to use Gerrit?

**Comment by SanderRonde** [comment]
Ah I thought I had a basic readme/setup guide in place but I didn't. I added one to `README.md`. Just checking but did you configure `gerrit.auth.username` and `gerrit.auth.password`? If you have a `.gitreview` file in the root of your repo that's all you'll need to configure. Do you have such a file? Also are you getting any errors? If not can you go to the `OUTPUT` panel in VSCode and select "Gerrit" from the dropdown and let me know what you see there?
