### ISSUE TITLE
Minimum version of Gerrit

### ISSUE THREAD

**Issue by felipecrs** [SanderRonde/VSCode-Gerrit#25]
Hi! 👋

I would just like to say that I'm watching your project. Congratulations on the initiative, I'm sure it's going to help lots of people going forward.

Today I tried to configure your extension against the Gerrit server which our company uses, and unfortunately it didn't work. I suspect it's because we are running an outdated version of Gerrit, which lacks many APIs or resources which you would otherwise rely on.

We are using Gerrit 2.14.

I have some suggestions for you:

1. Any plans to support such old Gerrit versions? For example, there are no such thing as WIP changes (instead there are Draft changes). There are no APIs for "My list", but there are APIs for "incoming reviews" for example.
   I honestly would advise you not to support versions of Gerrit which are EOL (such as 2.14), and instead focus on the forward development of the extension. But if you think it's not a big deal to support older versions, let me know. I can help you. PS: We plan to update Gerrit to 3.4 in December of 2022.

2. If there are no plans to support older versions of Gerrit, I recommend you add an extra check during the extension startup: check for the minimum version.
   So, instead of throwing multiple errors (because the server can't handle what the extension is asking for), first check if the Gerrit version matches the minimum version the extension needs, and if not, simply throw a notification message letting the user know that (and do not proceed with the extension startup).
   
3. As an alternative to 1, perhaps, we could check which features of the extension require newer versions of Gerrit. Knowing that, I think it would not be complicated to simply disable them.

What do you think?

**Comment by SanderRonde** [comment]
Good point! I think option 1 is indeed not really worth it. It would be too much effort for an (at the moment) relatively small extension when it comes to users. Option 3 would be ideal but it looks like it's a bit hard to find exact API versioning and the supported fields for every version of gerrit so this is a bit hard to backfill. I do intend to do it this way in the future (for example the commenting feature is already gated behind a minimum version of `3.5.0`).

I've decided to go with option 2. With these changes, if you're **below** version `3.4.0` (the latest non-EOL version) you'll get an on-signup message. You can then go with "try anyway and accept errors" or leave it be and stop further extension execution. I think this does indeed inform and prepare users a lot better.

Thanks for the suggestion and for thinking along (and hopefully the extension can help you out after december)! The new changes should be live soon.
