### ISSUE TITLE
Could this support older Gerrit versions?

### ISSUE THREAD

**Issue by phudson** [SanderRonde/VSCode-Gerrit#28]
At work, we have 2.16 ("obsolete with exceptions"), and no plans to upgrade any time soon.

Is it even feasible to consider changing this extension to work with that version?

**Comment by SanderRonde** [comment]
I think it's not really worth it to support older versions (especially ones that are a major release lower), also given that these older versions are already marked as obsolete. The hardest part probably is figuring out what is broken for each version. I can't really find a comprehensive list of API changes for gerrit ([the changelog ](https://www.gerritcodereview.com/3.4.html#rest-apis) just lists that _something_ changed in a subset of a certain endpoint) so I'd have to manually install each older version and walk through the entire extension to find things that may not work. With such a list I'd probably do it. I'd assume that the changes aren't _that_ major so it's probably not that much work, but for the time being I'll leave just the latest version(s) supported.

I'll close this issue for now but of course you're free to keep commenting (maybe you've even found such a list 😉).

**Comment by phudson** [comment]
Fair enough
