### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by 29ayush** [SanderRonde/VSCode-Gerrit#29]
Hi can you add some documentation. 

Like What's the difference between quick checkout and checkout, and other usage documentation. 

Also one issue I am facing is code browsing, I want to able to code browse when in review panel mode. 
If I see that a new function is added I want to be able to press F12 and see the usage, go to file . 
I don't want to open the file myself, and then browse, because then I can't see the changes highlighted in green. 
Is it possible?

**Comment by 29ayush** [comment]
Yes. Readme would be the best place.

> For your second point, I'm pretty sure that's not possible now. It's a feature I also miss quite often but it just seems to be a limitation of VSCode's diff view. If it's going to happen, the VSCode team is the one to do it since I'm pretty sure an extension can't fix that.
I see. that's sad.

**Comment by SanderRonde** [comment]
Thanks for the info! Will try to update the readme some time this week or next week.

**Comment by 29ayush** [comment]
As a workaround for code browsing, Is it possible to have a redirector someplace ? 
I mean let's say I have checked out the change, and I am doing a diff view, (review panel), 
I am on Line206:FileXyz, then something I can click which in a new tab opens FileXyz:Line206. 

I don't see an option currently 
I am allowed to open by right click modified file and original file, but they don't apparently correspond to actual local file.

**Comment by SanderRonde** [comment]
I'm pretty sure that's also not possible. The right-click menu in diff files is very limited so I doubt extensions can add to it. Would also be kind of hard to put such a button somewhere else, since it should ideally just open the highlighted line.

**Comment by SanderRonde** [comment]
I've added some more documentation in the README file so I've closed the issue for now. Please re-open it if could still be improved or if you feel your other question has not been fully answered.
