### ISSUE TITLE
Support for VSCodeWeb

### ISSUE THREAD

**Issue by Justman10000** [SanderRonde/VSCode-Gerrit#30]
It would be ridiculous, if the extension is not also available for the web version...

**Comment by SanderRonde** [comment]
Hi, there are some pretty hard to overcome issues that make it so this extension is not available for the web version.
- it uses the `git` and `git-review` binaries that are both not available on web.
- it uses http requests to talk to gerrit, but most gerrit setups don't support CORS. This means that any http request from a browser context is rejected by the server.

Will be closing this issue for now unless you have some suggestions :)
