### ISSUE TITLE
[feature] Add support for localization with vscode-loc installed.

### ISSUE THREAD

**Issue by hwhsu1231** [SanderRonde/VSCode-Gerrit#38]
### Feature Request

There is a VSCode Localization Extension provided by Microsoft, [vscode-loc](https://github.com/microsoft/vscode-loc).

According to: https://github.com/microsoft/vscode-loc/issues/894#issuecomment-1160994995

It seems that we should ask particular extensions to support its localization.

Can this extension support the localization with the vscode-loc installed?

**Comment by SanderRonde** [comment]
Hmm that would require me to turn every string in the extension into a replaceable. That honestly sounds like a lot of work, especially considering I didn't build the extension with that idea and so don't know the location of all strings. For that reason I'm unfortunately going to have to decide not to do this.
