### ISSUE TITLE
When I submit a review without writing a review-level comment, a wild "This change is ready for review." appears

### ISSUE THREAD

**Issue by Mackiavelli** [SanderRonde/VSCode-Gerrit#39]
Scenario: I am making a gerrit review within VSCode. I add comments on lines and selections within lines. When I submit the review using the "Review" sub-panel in the "Gerrit" panel, in the box that says "Say something nice..." I don't enter anything (leaving it blank). However, when the review is submitted to Gerrit, it seems that my review-wide comment is not blank, but always "This change is ready for review.". This has happened on more than one review where I haven't entered anything in the comment box

Gerrit version:  (3.5.1) 
Gerrit plugin version: v1.2.11
VSCode info: 
Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by Mackiavelli** [comment]
The end result is:
![image](https://user-images.githubusercontent.com/7420641/231205872-c67fdcbc-a0cf-4151-8978-da0fb6e2a74c.png)
When I click submit on the "Review" sub-tab when it looks like:
![image](https://user-images.githubusercontent.com/7420641/231206093-563df7ab-7d43-4e37-9e45-a0f8159de8b6.png)

**Comment by Mackiavelli** [comment]
> Are you sure that only happens when using this extension? I get the exact same thing when using the web UI. Or maybe my instance is configured differently...

Yes, this only happens through the plugin and not the web UI. The only way to force this to happen in the web UI is if I had a review which was marked as "Work in Progress" and then I clicked on "Start Review". It posts a comment automatically with the same message. But this doesn't happen when I click on "Reply" and then do a +1/+2 without adding anything in the comment box.

**Comment by SanderRonde** [comment]
Sorry for not responding for such a long time, was a bit busy. I found the issue and fixed it :) For some reason the Gerrit API always posts "this change is ready for review" when marking a change as ready, even though it says it'll only do something if that is true **and** the change is in review.
