### ISSUE TITLE
Make "Push for review" branch configurable

### ISSUE THREAD

**Issue by benclauss** [SanderRonde/VSCode-Gerrit#40]
I always `git push origin HEAD:refs/for/master` irrespective of the branch I am on. However, the "Push for review" button/action will always push to `my-branch`.

**Comment by SanderRonde** [comment]
Ah yes, "push for review" essentially just runs "git review" in the terminal. I could change but it sounds like quite a bit of added complexity for something that (I think) not many people do and that doesn't have too big of an impact. Or is this a bigger issue?
