### ISSUE TITLE
Gerrit request to ... failed

### ISSUE THREAD

**Issue by ChandlerEN** [SanderRonde/VSCode-Gerrit#41]
Hello,

I've recently installed your extension and trying to make it work but I struggle to do so.

Everytime I try to launch the extension I receive two errors :

![Untitled](https://github.com/SanderRonde/VSCode-Gerrit/assets/90051946/896d74e8-0729-4c62-8de7-c73bbcd191dd)

When I type the URL "username@gerrit.com/a/accounts/self" myself in the browser I do receive the "self.JSON" and "version.JSON" files.

The 'gerrit.auth.username' and 'password' should be right and I've also installed the gerrit-review package with pip.

Am I doing something wrong ?

Thank you.

**Comment by SanderRonde** [comment]
I think you're not supposed to put the username and the @ in the URL itself. That should be the the username. The host should just be everything after the @. Let me know if that works :) 

The reason it works in your browser (I'm not entirely sure but quite) is that when you're typing “user@website.com" you're not visiting "http://user@website.com", instead your browser does something special and sends your username as an authentication header and just does a regular request to "website.com".

Maybe good to know, in the edit history I can still see the original uncensored screenshot. I won't do anything bad with it but if you'd really like to remove it from the web I'd remove this issue after it's been resolved. If you want to I can remove this paragraph too so it doesn't call attention to it.

**Comment by ChandlerEN** [comment]
Thank you for your answer and your warning on the edit history. I deleted my previous post.

I tried your suggestion but unfortunately it didn't worked.

I tried without the "@", with the project path, with ssh but no result 😥

**Comment by SanderRonde** [comment]
What happens when you visit the web version without the `@`? Which version of the path do you use to view your dashboard? What happens when you append `/a/accounts/self` to that and visit it in the browser?

**Comment by ChandlerEN** [comment]
On the browser, if I remove the "@" it redirect me to the dashboard and the url is "gerrit.example.com/dashboard/self".

If I add "/a/accounts/self" it gives me Error 400 and not found.

**Comment by SanderRonde** [comment]
So if you try gerrit.example.com/a/accounts/self you get a 400? In that case maybe the HTTP API has just been disabled on your gerrit instance. Can you check with your administrator what your gerrit setup is?

**Comment by ChandlerEN** [comment]
Actually the browser version works fine, I get the JSON file.

When put as the URL for the extension though, still request fail.

**Comment by SanderRonde** [comment]
Can you open the logs (select gerrit in the "output" panel) and post what it says?

**Comment by ChandlerEN** [comment]
It says :

GET request to "ssh://gerrit.example.com/config/server/version"
UnsupportedProtocolError: Unsupported protocol "ssh:"   
GET request to "ssh://gerrit.example.com/a/accounts/self"
UnsupportedProtocolError: Unsupported protocol "ssh:"   
Invalid response

**Comment by SanderRonde** [comment]
Hmm where did the ssh come from, did you put that somewhere in the settings? It should be using regular old http

**Comment by ChandlerEN** [comment]
I've put ssh nowhere in the settings.

Might be because of another extension, I'll look into it.

**Comment by SanderRonde** [comment]
Could be that it's just taking the settings in your `.gitreview` file. Does that include `ssh` by any chance? If so, you can override it by setting `gerrit.auth.url`.

**Comment by ChandlerEN** [comment]
My project does not include any .gitreview

**Comment by ChandlerEN** [comment]
Ok I retried this morning and it seems to be using the http protocol this time 😀

However I still have errors :

"__GET request to "https://gerrit.example.com/config/server/version"
RequestError: unable to verify the first certificate   
GET request to "https://gerrit.example.com/a/accounts/self"
RequestError: unable to verify the first certificate   
Invalid response__"

**Comment by SanderRonde** [comment]
Looks like the webserver is [wrongly configured then](https://stackoverflow.com/a/60020493/2078892). You can ignore this by enabling the `Gerrit: Allow invalid SSLCerts` setting (I think), but this should be fixed regardless.

**Comment by ChandlerEN** [comment]
Your solution works !
I can now view informations and stuff about my gerrit. The push for review doesn't work though, is it normal ?

I'll talk about the ssl certificate with an administrator.

**Comment by SanderRonde** [comment]
Awesome! Push for review should work. It basically just runs `git review` in a terminal. What is your normal method of pushing for review?

**Comment by SanderRonde** [comment]
That should work, can you check the logs again? :)

**Comment by ChandlerEN** [comment]
It does nothing.

I click on this button

![image](https://github.com/SanderRonde/VSCode-Gerrit/assets/90051946/80cc0a4c-db2f-43b2-b61e-4cd0bed484dd)

But nothing happen in the gerrit output, just the GET request for when I checked the extension window :(

**Comment by ChandlerEN** [comment]
It does nothing.

I click on this button

![Untitled](https://github.com/SanderRonde/VSCode-Gerrit/assets/90051946/ebaae8dd-8c48-43ec-b507-0bf58f84e6cc)

But nothing happen in the gerrit output, just the GET request for when I checked the extension window :(

**Comment by SanderRonde** [comment]
Ah you're right... What happens when you just run `git review` in your terminal?

**Comment by ChandlerEN** [comment]
It says "Creating a git remote called 'gerrit' that maps to:" but there is a merging problem.

**Comment by SanderRonde** [comment]
Can you fix that problem? Basically when you get `git review` to be running normally, the button will work normally too.

**Comment by ChandlerEN** [comment]
There are still small issues like not being able to Checkout change but from the log I think it's related to the configuration of the gerrit repository so I might be able to handle it.

Otherwise, is it possible to add "+1" or "+2" to reviews with the extension ?

Other than this, everything is okay and the issue can be close 😊

Thank you so much for everything!

**Comment by SanderRonde** [comment]
Checkout basically just runs `git-review -d ${patchNumber}`. If you get that working then the button will work too :)
You can leave a vote by checking out a change, then opening the gerrit panel on the left, then the `review` panel on the bottom and voting. I think you need to have either checked out a change or already left a comment, not entirely sure.

Will close the issue for now but feel free to ask more questions if you need help.

**Comment by ChandlerEN** [comment]
Hello again! Quick question, is it possible to submit a "Ready to submit" commit with the extension ?

**Comment by SanderRonde** [comment]
Yes, just clicking the "send" button in the review panel should take it from WIP to ready-for-review I think

**Comment by SanderRonde** [comment]
Ah no that's currently not possible from the extension. I'm kind of reluctant to add it since it's a pretty consequential operation, so I don't think it's a bad idea to leave that web-only for the time being. Am open to adding it though if people exclusively use the extension and not the web version.

**Comment by ChandlerEN** [comment]
Actually it was indeed my intentions to include in our workflow the usage of Gerrit entirely through the extension.

If you intend to do so, we will happily use it!

**Comment by SanderRonde** [comment]
That does sound like a good idea. I've started implementing the feature but can't really test it (easily) myself. Could you check for me whether this version of the extension works and allows submitting? It should show a "submit" button in the review panel if a change is submittable. Please install the associated `.vsix` file (that I've renamed to `.zip` because github does not allow uploading of `.vsix` files) and let me know if it works :). You can install it by dropping it into your `extension` tab, or dropping it into your workspace, right-clicking and hitting "install VSIX".

[vscode--gerrit-1.2.12.zip](https://github.com/SanderRonde/VSCode-Gerrit/files/12136472/vscode--gerrit-1.2.12.zip)
