### ISSUE TITLE
Autenticcated config/server/version request 

### ISSUE THREAD

**Issue by ishifman-nvidia** [SanderRonde/VSCode-Gerrit#45]
Hi 
in my organization the Gerrit server doesn't permits anonyms users
so even the get version should be authenticated  
https://<gerrit_url>/a/config/server/version
it seems that current request is not supporting this :
`GET request to "https://<our_gerit_server>/config/server/version`
is it possible to handle this?
maybe by adding a flag in settings to support getGerritVersion with authentication? 
or maybe by trying to call getURL with and without authentication?

Thanks

**Comment by SanderRonde** [comment]
It does do one initial unauthenticated call to `/config/server/version` but it continues the flow if this request fails. It does indeed show a warning while it shouldn't. I fixed that part and released a new version with it (`1.2.14`)

The extension will function the same as before though, all API requests that are actually depended on are already all authenticated.
