### ISSUE TITLE
Editing a created comment makes it disappear

### ISSUE THREAD

**Issue by JohnnyMorganz** [SanderRonde/VSCode-Gerrit#46]
Steps:
1) Create a comment on a file
2) Save as unresolved
3) Click the edit button to edit the comment
4) Save edit

Expected result:
- The edited comment shows

Actual result:
- The comment disappears and cannot be seen again. Note that the comment still exists, and the edit worked, since if I go to the gerrit webpage it still shows up

Thanks for your work on this extension, its pretty cool!

**Comment by SanderRonde** [comment]
Hmm I can't really reproduce this one. Can you provide a video maybe? I'm probably missing some steps.

And thank you for the kind words :)

**Comment by SanderRonde** [comment]
Will be closing this issue since it's gone stale

**Comment by JohnnyMorganz** [comment]
Yup, sorry about that - I was meaning to reply but I guess I forgot. But I can no longer reproduce my original issue :)

**Comment by SanderRonde** [comment]
Ah well all good then :)
