### ISSUE TITLE
Gerrit: found multiple gerrit roots

### ISSUE THREAD

**Issue by rustyx** [SanderRonde/VSCode-Gerrit#48]
Every time I open my workspace, I am presented with this warning

"_Gerrit: found multiple gerrit roots, please choose which one you'd like to use the extension with. (you can change this later with the "Gerrit: change git repo" command_"

Then I have to select the project. Which is always the same. So it's quite annoying. Yes, I have multiple Gerrit projects, but there is always one I'm actively working on.

Hence hereby a request to add a way to remember my choice.

**Comment by SanderRonde** [comment]
Hmm does it not save this to any of your settings? Either workspace or global settings (the former is more likely). If not I'll take a look and fix it.

**Comment by rustyx** [comment]
It does not. Also I couldn't find any setting for it to set manually.

**Comment by SanderRonde** [comment]
Ah strange, it worked for me. The `gerrit.gitRepo` setting is the one that controls this behavior. Can you set that setting, with its value being the full path to the repo you want to use?

**Comment by JohnnyMorganz** [comment]
Interestingly, I also used to experience this issue, but I cannot reproduce it right now 🤔. I have `gerrit.gitRepo` set in my workspace settings. Not very helpful comment (sorry!), but it does seem somewhat flaky. Will see if I stumble across it again.

**Comment by SanderRonde** [comment]
Definitely a helpful comment :) It does show that it's not just one person experiencing it. I think I may have found out why this particular setting is a bit flaky, it's because it's the only setting that is not set at a global level and I wasn't explicitly supplying a level at which to set the setting. I'll change and release a new version, let's see if that helps.

**Comment by SanderRonde** [comment]
FYI version 2.1.16 has been released, which contains rusty's fix

**Comment by rustyx** [comment]
Thanks for the quick action, but the issue is still present. It looks like the fix didn't make it to the 1.2.16 release, the tag is just before the merge of the PR:

![image](https://github.com/SanderRonde/VSCode-Gerrit/assets/1296899/b303d740-c981-4733-b2cc-80254b70026d)

Can you perhaps make a new release?

**Comment by SanderRonde** [comment]
Ah my bad I didn't pull before making the release. `1.2.17` it is then, release should be live now
