### ISSUE TITLE
Posted comments marked as Draft until Window reloaded

### ISSUE THREAD

**Issue by FlipB** [SanderRonde/VSCode-Gerrit#52]
When making comments in VS Code the comments are marked as "_Draft_".
I would expect the "_Draft_" tag to be removed after hitting "Send" on the review.

As it is now, the comments are still shown as _Draft_ in VS Code long after they have been posted to Gerrit.

"_Gerrit: Refresh Changes_" action does not help.
After "_Reload Window_" action it does show the comment state correctly.

(however after a _Window Reload_ action it shows the same comment thread duplicated 13 times (!) in VS Code, but clicking on the review in the Gerrit pane refreshes the comments which removes the duplicates)

**Comment by FlipB** [comment]
Quick turn-around!
I tested 1.2.20 and when posting the comment it did indeed change and is no longer displayed as Draft.
However, in it's place i got about 80 (!) instances of the same comment thread.
Perhaps this is a different issue - should I create another issue?

In the logs i see a lot of  calls to these two endpoint over and over again (575 consecutive lines)

GET request to "https://<gerritinstance>/changes/<change>/comments/"
GET request to "https://<gerritinstance>/changes/<change>/drafts/"

**Comment by SanderRonde** [comment]
Ah yeah that sounds pretty bad. I'll just re-open this issue since my fix might have caused that. I'm assuming that you've censored the URLs you posted and they actually point to the same change right?

I'll try and get this fixed soon. For some reason I couldn't replicate the duplication issue before so I hope I can now. If not I might ask you for some more info/steps on how to reproduce.

**Comment by FlipB** [comment]
Yeah, I censored the URL's and apparently they didn't render correctly in github due to that. Updated the URLs.
I'm using the Gerrit plugin via "Remote - SSH" plugin if that could affect things (to clarify Gerrit plugin is installed on the remote host, which is accessed via SSH).

**Comment by SanderRonde** [comment]
I think I've fixed the issue in the latest version. I'm not entirely sure since I can't replicate it so do let me know if it's still present!
