### ISSUE TITLE
Checkout feature is broken with Gerrit 3.9.1

### ISSUE THREAD

**Issue by lcharlois-neotys** [SanderRonde/VSCode-Gerrit#54]
Hello,

We upgraded our gerrit server to the latest version (3.9.1)
Since that I'm not able to checkout review using the extension.

It looks like the gerrit API has changed.

Before API was returining document like this
```json
{
  "id": "my-repo~develop~Iea56eab37b4b11151c579000fc9fdcffd4b6a4b3",
  "project": "my-repo",
  "branch": "develop", 
```
now it returns document like this
```json
{
  "id": "my-repo~12318",
  "triplet_id": "my-repo~develop~Icdf3ed8e5f13b8c95f7a3bddc74892fb010ef2ad",
  "project": "my-repo",
```

What I see in the extension logs let me think this is the cause:

```
Tried to run "git-review -d "my-repo~12244"", but failed
Stdout: my-repo~12244

Stderr: 
```
I will say the issue is here coming from this funtion: https://github.com/SanderRonde/VSCode-Gerrit/blob/ad550bb3e62d651980f54c382f1ff8929a7243dd/src/lib/git/git.ts#L294

I will propose a PR to fix that issue.

**Comment by SanderRonde** [comment]
Version `1.2.25` with the fix is live!

**Comment by lcharlois-neotys** [comment]
Just to let you know, I've installed the new version and checkout is now fixed.
Thanks.

**Comment by SanderRonde** [comment]
Awesome, thanks for letting me know
