### ISSUE TITLE
Compatibility with VsCodeVim extension

### ISSUE THREAD

**Issue by moon6pence** [SanderRonde/VSCode-Gerrit#56]
Do you think inline comment code view is compatible with Vim extension?
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

When I tried with Vim extension, 
- I clicked one of source code from changes tree
- It shows comments and diff properly
- As soon as I move mouse cursor to source right panel of code editor, gerrit comment disappears. 
- When I start editing with Vim extension, gerrit comment appears again I cannot type anything in editor.
- After I change focus to other window (other than vscode) and back, everything is fine - both comment and editing works.

vscode: Version: 1.85.1 (Universal) in MacOS
Gerrit extension: v1.2.28
Vim extension: v1.27.2

Please don't hesitate to ping me if you need more information.

**Comment by SanderRonde** [comment]
Hmm that shouldn't be happening. The Gerrit extension is using the native Comment API so nothing too fancy. Could you maybe try the Github VSCode extension? That uses the same API so it might have the same issue. If not maybe it's this extension's fault.

**Comment by moon6pence** [comment]
I also think it might not directly related with Gerrit addon, still not 100% sure when it freezes with certain situation. 

I will try to test with other addon as like Github you suggested, and let you know if there is more specific and reproducible situation. Feel free to resolve issue if you don't hear from me for long time.

**Comment by SanderRonde** [comment]
Thanks! I'll resolve it for now (otherwise I'll forget) but feel free to re-open if you've got some more info
