### ISSUE TITLE
POST calls not working - Gerrit 3.8.2

### ISSUE THREAD

**Issue by DarinVenkovSEE** [SanderRonde/VSCode-Gerrit#58]
Hello,

I have configured my Gerrit plugin in VS Code with the repository URL (gerrit.auth.url) and my Authentication Cookie (gerrit.auth.cookie) for Gerrit and most of the REST requests work except for the POST calls:

```
POST request to "https://<Gerrit-host>/r/a/changes/<repo>~master~I4df7714d8f7c0d0629a3b8ae69566987e5a849ef/revisions/f5f6d54a5499f0cdffb5b0b35bf528bfbdf5dc7b/review"
HTTPError: Response code 403 (Forbidden) 403 [object Object] Invalid authentication method. In order to authenticate, prefix the REST endpoint URL with /a/ (e.g. http://example.com/a/projects/).
```

I don't know if only the authentication cookie is enough for the POST calls or if they need username and password to do basic authentication.
I tried configuring the username (gerrit.auth.username) and password (gerrit.auth.password) in the Gerrit plugin but then the other REST calls that were previously working are no longer working with this error:

```
GET request to "https://<Gerrit-host>/r/a/accounts/self"
HTTPError: Response code 403 (Forbidden) 403 [object Object] Forbidden
Invalid response
```

So far I haven't found the correct configuration to make all REST calls (GET and POST) to work.

Best regards,
Darin Venkov

**Comment by SanderRonde** [comment]
Hi is the `/r` part of your gerrit host? As far as I know it should not be part of the URL and it might be the reason that you're getting these errors. The cookie method should work just fine with POST calls (works for me at least) and so should logging in with a username and password. A `forbidden` error is probably related to the configuration of your gerrit host. I do find it strange that GET requests are succeeding though... Maybe the changes are publicly visible without login and it only asks for credentials once you start changing things (aka POST requests).

**Comment by svogt** [comment]
As I'm the admin of the server :) Yes, we host Gerrit below a path (/r) and I'm confused as well to why some endpoints work and others don't.

I've tested with Incognito Browser Windows as well as curl on the command line (supplying basic auth credentials there or via .netrc) and the URLs work just fine. I get the usual API response (the one with the 3 invalid JSON chars at the beginning) and then the requested info (be it the own account or the review info)...

**Comment by SanderRonde** [comment]
Will close this issue in favor of #57 since I'm pretty sure it's the same issue
