### ISSUE TITLE
[Question] Configure Dashboard column for a Gerrit panel

### ISSUE THREAD

**Issue by LazyRen** [SanderRonde/VSCode-Gerrit#65]
Hello @SanderRonde, thank you for a great extension.

This is something I indeed has been looking for.

One question/feature request (if not possible) is
would it be possible to show a Change Table Columns from a Gerrit?

For example, I can choose which information to be shown on my Gerrit Dashboard,
but from a extension sidebar, onlything I can check is a `commit title` & `owner`.
![Screenshot 2024-04-24 at 6 13 54 PM](https://github.com/SanderRonde/VSCode-Gerrit/assets/8989837/e831d6b3-d55b-4719-a6ed-50403345a0df)

Having this feature would be very helpful as I have many cherry-picked changes for different branch and it's hard to distinguish them with current UI.

Thank you!

**Comment by SanderRonde** [comment]
Yeah sounds like a good idea. I'm not entirely sure how best to visualize this though... On the web UI you have a very wide screen table layout that allows you to easily show everything. In the VSCode UI you have a tiny sidebar. What would you think is a fine solution? Showing the information on-hover, making it replace (or prefix) the title? Having a sort of sub-entry below the title for each additional fields (so vertically stacking)? Or maybe a dedicated table view?

**Comment by LazyRen** [comment]
Thank you for a very fast response.

> Showing the information on-hover, making it replace (or prefix) the title

Seems reasonable to me.

If it can be configurable by a user, I would have `[branch] Title (author)` which would be perfectly fit within a sidebar as it only replaces `change-id` with a `<branch_name>`.

e.g.)
```
#12345678 [Fix] Bug-123456 Fix something something by LazyRen

to

[MyBranch] [Fix] Bug-123456 Fix something something by LazyRen
```

If user wants to put more info into a Dashboard, he/she would also increase the size of a sidebar or configure to fit within a current sidebar so this would be a good way to do so.
