### ISSUE TITLE
Filter reviews for one (current git repo) project only

### ISSUE THREAD

**Issue by thu2004** [SanderRonde/VSCode-Gerrit#67]
I have a .gitreview file with the following content
```
[gerrit]
host=https://my-gerrit.abc.com
project=sun/project_1
```
My aim is to solely view reviews linked to this specific project upon accessing the Gerrit panel, rather than all the projects I can access. Have I overlooked a particular setting for this? Or is there a method to integrate such support?

Upon inspecting the code, I noticed that the 'project' property from the gitreview file is solely used in the openOnGitiles function located at src/lib/gitles/gitles.ts.

**Comment by SanderRonde** [comment]
That's a good point actually, I'll change it so that it only shows changes in the current project by default.

**Comment by SanderRonde** [comment]
Now live in version `1.1.35` :)
