### ISSUE TITLE
Comments doubling

### ISSUE THREAD

**Issue by Mattadore** [SanderRonde/VSCode-Gerrit#72]
I'm having an issue with all comments appearing twice. I am not sure of the cause.. though it seems like it should be straightforward to just sort comment hashes and filter duplicates? If you can identify why it's loading twice, that would be great too. I'm in the environment we've discussed before (multi-project monorepo, gerrit file path is not from workspace root, AOSP basically)

I wish I had more helpful info but I genuinely have no idea what the cause is. Let me know if there's anything I can do to help debug

**Comment by Mattadore** [comment]
JK issue is gone after update

**Comment by Mattadore** [comment]
Actually the dupes are back, they don't show up immedlately when the editor loads it takes a while.

**Comment by SanderRonde** [comment]
I think I've now actually fixed it. I managed to reproduce it quite consistently and think I know what the issue was. I'll be including it in the next version once I've gone through all the other issues.
