### ISSUE TITLE
Unresolved/Resolved comment filter does not filter

### ISSUE THREAD

**Issue by Mattadore** [SanderRonde/VSCode-Gerrit#74]
Even if I disable both, I still see all the comments available :(

**Comment by SanderRonde** [comment]
Which filter do you mean? Maybe I've forgotten some parts of the extension :)

**Comment by Mattadore** [comment]
![image](https://github.com/user-attachments/assets/38d2d09f-636d-4ddb-afce-008e6c241958)
![image](https://github.com/user-attachments/assets/b553d110-7846-479d-ba74-05f49c8aa41b)
This button, under the comments tab

**Comment by SanderRonde** [comment]
Ah yeah that's not something I added... Think that's native to VSCode and a pretty new feature (at least it wasn't there when I built the extension). Will try to add support for it though.

**Comment by SanderRonde** [comment]
Yeah it was indeed something new, but luckily pretty easy to integrate since the extension already supported it. Should be live in the next version (`1.2.42`)
