### ISSUE TITLE
Send a single reply on a comment is not working

### ISSUE THREAD

**Issue by joguy56** [SanderRonde/VSCode-Gerrit#80]
First I must applause for this fabulous extension ! Waiting for the multi-repo ! 

I am not sure to understand the way of comments are working.

I make a comment, it sent as draft into gerrit.

Then if I want to send them officially, the button seems not to work. It just does nothing.

I can’t even get one log from the gerrit console.

Am I missing something to do somewhere ?

Jonathan

**Comment by SanderRonde** [comment]
Hi thanks for the kind words!

When saying "the button does not work" which button do you mean? Do you mean the "Send and Start Review" button in the review panel? That button should work (at least it does for me) and should produce logs. If not maybe it's somehow broken in your case, I could figure out what's wrong by adding some debug logs that should help me nail it down.

**Comment by joguy56** [comment]
Hello,

For sure,this one is a missing gitreview file issue.

Maybe it is the reason also for the other topic!

I Wille check it out.
