### ISSUE TITLE
Explain the checkout workflow for making a new fresh review

### ISSUE THREAD

**Issue by joguy56** [SanderRonde/VSCode-Gerrit#81]
I would like to post a new review directly from the extension.

First I made a commit. The commit-msg contains the ChangeId, but the gerrit extension seems to be lost as soon as the new commit exists since it is trying to fetch a review that does not exist yet.

I tried to push it with the button "Push for review" but nothing happens.

Can you explain the good workflow to create new reviews ?

Thanks a lot for your work

**Comment by SanderRonde** [comment]
That should indeed push it for review by running `git review` in the terminal under the hood. Do the logs show anything at all? Is there any notification or something that pops up?

**Comment by joguy56** [comment]
Yes it is also a missing gitreview file issue indeed.

Thanks a lot for quick replying!
